modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="atarikafa_heykelleri"
version="1.0.0"
displayName="AtariKafa Heykelleri"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="baran, MCreator"

[[dependencies.atarikafa_heykelleri]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




